#!/bin/bash

### scaler 部署环境 ###
test_env="192.168.177.89:1818"

function delete_instance(){
[[ $# != 1 ]] && echo "Please input space id" && exit;
### scaler创建缓存云实例的参数 ###
requestId="0ac543b5-0f1d-44eb-ac47-757105a2781"$1
spaceId="0ac543b5-0f1d-44eb-ac47-757105a2781"$1
operationId="0ac543b5-0f1d-44eb-ac47-757105a2781"$1

echo "[INFO] Scaler删除缓存云实例"
test_case="curl -s -XPOST --data '{\"operationId\":\"${operationId}\",\"requestId\":\"${requestId}\",\"spaceId\":\"${spaceId}\"}' \"http://${test_env}/delete\""

echo "${test_case}"
echo ""
result=`eval ${test_case}`
echo "[RESULT] ${result}"
echo ""
}

for((i=10;i<31;i++))
do
	delete_instance $i &
done
