#!/bin/bash

### 线上环境-hb  ###
env_test="jmiss-mongo-prod-hb.jcloud.com"
wait_time="5"

### 用户信息 ###
token="2k+pS3qIBB6TLilR1S7qxwBmM8z0WEZTbk7O8xQuZPGAiG2II5aMD8AzWJdqXKcI"
pin="242d9895529bf5ce45a672a3b8bfb212"

### 参数信息  ###
vpc_id="vpc-cv5h3h0gru"
subnet_id="subnet-3zbd5vstt7"
flavor_id="12704fa2-0f52-4859-b48f-6db86603c248"
password="A7991892011fd761"
image_version="mongodb-3.2"
os_user_info="tenantId:6638663763623865653634363438353238373736336562333463333838326162;tenantName:6a636c6f75645f3030406a636c6f75642e636f6d;userId:3237623037396333353435353430343262316366363862346234633566633862;password:6a636c6f75645f3030406a636c6f75642e636f6d"

function create_mongo_instance(){
	### 创建实例  ###
	echo "[STEP1] 创建mongo实例"
	test_case="curl -s -H\"auth-Token:${token}\" -H\"Content-Type:application/json\" -XPOST --data '{\"vpcId\":\"${vpc_id}\", \"subnetId\":\"${subnet_id}\", \"flavorId\":\"${flavor_id}\", \"password\":\"${password}\", \"spaceType\":1, \"dbVersion\":\"${image_version}\", \"osUserInfo\":\"${os_user_info}\"}' \"http://${env_test}/v2.0/${pin}/clusters\""
	echo "${test_case}"
	echo ""
	result=`eval ${test_case}`
	code=`echo ${result} | jq '.code'`
	[[ ${code} != 0 ]] && echo "Cannot create a mongo instance" && exit 1;
	echo "[RESULT] ${result}"
	echo ""
	space_id=`echo ${result} | jq .attach.spaceId`
	[[ ${space_id} == "" ]] && echo "There is no instance to be created sucessfully"
}

for((i=0;i<5;i++))
do
	create_mongo_instance &
done

exit 0
