#!/bin/bash

current_path=`echo $(pwd)`
delete_script_path=${current_path}"/rm_delete_docker_containers"

test_env="192.168.177.89:8888"

memory_size_1G="1073741824"
memory_size_2G="2147483648"
memory_size_3G="3221225472"
memory_size_4G="4294967296"
memory_size_10G="10737418240"

zone_id="1"

concurrent_num=10

function create_delete_docker_container(){
echo "[INFO] RM创建docker containers"
test_case="curl -s -XPOST --data '[{\"name\":\"master1\",\"mem\":${memory_size_1G},\"load\":5,\"net\":100,\"zoneid\":${zone_id},\"exip\":[],\"exname\":[]},{\"name\":\"slave1\",\"mem\":${memory_size_1G},\"load\":5,\"net\":100,\"zoneid\":${zone_id},\"exip\":[],\"exname\":[\"master1\"]}]' \"http://${test_env}/redis/create\""

echo "${test_case}"
result=`eval ${test_case}`
master_ip=`echo "${result}" | jq .Results[0].Ip`
master_port=`echo "${result}" | jq .Results[0].Port`
slave_ip=`echo "${result}" | jq .Results[1].Ip`
slave_port=`echo "${result}" | jq .Results[1].Port`

echo ""

#echo "[INFO] RM删除docker containers"
eval ${delete_script_path} ${master_ip} ${master_port} ${slave_ip} ${slave_port}
echo ""

}

for((i=0;i<${concurrent_num};i++))
do
#echo "[INFO] RM创建docker containers"
#test_case="curl -s -XPOST --data '[{\"name\":\"master1\",\"mem\":${memory_size_1G},\"load\":5,\"net\":100,\"zoneid\":${zone_id},\"exip\":[],\"exname\":[]},{\"name\":\"slave1\",\"mem\":${memory_size_1G},\"load\":5,\"net\":100,\"zoneid\":${zone_id},\"exip\":[],\"exname\":[\"master1\"]}]' \"http://${test_env}/redis/create\""

#echo "${test_case}"
#result=`eval ${test_case}`
#master_ip=`echo "${result}" | jq .Results[0].Ip`
#master_port=`echo "${result}" | jq .Results[0].Port`
#slave_ip=`echo "${result}" | jq .Results[1].Ip`
#slave_port=`echo "${result}" | jq .Results[1].Port`
create_delete_docker_container
echo ""

echo "[INFO] RM删除docker containers"
eval ${delete_script_path} ${master_ip} ${master_port} ${slave_ip} ${slave_port}
echo ""
done


