#!/bin/bash

#######################################################################
### DESC:为space_id设置ACL控制管理规则，并根据space_id查看ACL设置信息
### INTERFACE: http://ip:port/v1.0/{pin}/acl
### METHOD: PUT
### INTERFACE: http://ip:port/v1.0/{pin}/acl/{space_id}
### METHOD: GET
### AUTHER: guoli
### DATE: 06/09/2016
### VERSION: 1.0
#######################################################################

### 依赖：系统中安装jq ###

### 输入参数个数小于1，不执行本脚本 ###
if [ $# -lt 1 ];then
        echo "[WARNING]请输入space id"
        exit 0
fi

### 环境 ###
env_test="192.168.177.88"

auth_token="K1AwANjwaBmIWZBBHadr6oLC3AEIAkAtqhAJofH+ZZw="
auth_token_pin="64c8ddb08ad83c7b04fba541c3b085fd"

space_id="$1"

wait_time_long="5"

### Mysql数据库信息 ###
MYSQL_HOSTNAME="192.168.177.87"
MYSQL_PORT="3306"
MYSQL_USERNAME="tester"
MYSQL_PASSWORD="123456"
MYSQL_DBNAME="jimdb"
MYSQL_TABLENAME_TOPOLOGY="topology"

### 获取本机IP地址 ###
local_host_ip=`/sbin/ifconfig -a|grep inet|grep -v 127.0.0.1|grep -v inet6|awk '{print $2}'|tr -d \"addr:\"`
echo "[INFO] 本机IP: local_host_ip=${local_host_ip}"
echo ""

#mysql -h192.168.177.87 -utester -p123456 << EOF
#	show databases;
#	use jimdb;
#	select * from instance;
#	select * from topology;
#EOF

### 查询topology ###
sql_select_topology=`mysql -h192.168.177.87 -utester -p123456 << EOF
	use jimdb;
	select current_topology from topology where space_id=${space_id};
EOF`

### shard id ##
result_shardId=`echo "${sql_select_topology}" | awk '{if(NR == 2) print}' | jq .shards[0].shardId`
echo "[INFO] shardId=${result_shardId}"
echo ""

### master ip & port ###
result_master_ip=`echo "${sql_select_topology}" | awk '{if(NR == 2) print}' | jq .shards[0].master.ip`
echo "[INFO] master_ip=${result_master_ip}"
echo ""

result_master_port=`echo "${sql_select_topology}" | awk '{if(NR == 2) print}' | jq .shards[0].master.port`
echo "[INFO] master_port=${result_master_port}"
echo ""

### slave ip & port ###
result_slave_ip=`echo "${sql_select_topology}" | awk '{if(NR == 2) print}' | jq .shards[0].master.slaves[0].ip`
echo "[INFO] slave_ip=${result_slave_ip}"
echo ""

result_slave_port=`echo "${sql_select_topology}" | awk '{if(NR == 2) print}' | jq .shards[0].master.slaves[0].port`
echo "[INFO] slave_port=${result_slave_port}"
echo ""

concurrent_times="2"
for ((i=0;i<${concurrent_times};i++))
do
### 设置ACL访问列表 ###
echo "设置ACL访问规则"
test_cases="curl -s -H\"auth-Token:${auth_token}\" -H\"Content-Type:application/json\" -XPUT --data '{\"target\":[${space_id}],\"ips\":[\"${local_host_ip}\", ${result_master_ip},${result_slave_ip}],\"action\":\"allow\"}' http://${env_test}/v1.0/${auth_token_pin}/acl"
echo "${test_cases}"
result=`eval ${test_cases}`
echo "[RESULT] ${result}"
echo ""

code=`echo ${result} | jq .code`

if [ ${code} == "null" ] || [ ${code} != "1" ];then
	msg=`echo ${result} | jq .msg`
	echo "[ERROR] 【设置ACL访问列表失败】${msg}"
	echo ""
fi
done

sleep "${wait_time_long}"

### 查看ACL设置 ###
test_cases="curl -s -H\"auth-Token:${auth_token}\" -XGET http://${env_test}/v1.0/${auth_token_pin}/acl/${space_id}"
echo "${test_cases}"
result=`eval ${test_cases}`
echo "[RESULT] ${result}"
echo ""

code=`echo ${result} | jq .code`

if [ ${code} == "null" ] || [ ${code} != "1" ];then
        msg=`echo ${result} | jq .msg`
        echo "[ERROR] 【查看ACL访问列表失败】${msg}"
        echo ""
fi


### 设置ACL访问列表 ###
echo "设置ACL访问规则"
test_cases="curl -s -H\"auth-Token:${auth_token}\" -H\"Content-Type:application/json\" -XPUT --data '{\"target\":[${space_id}],\"ips\":[\"${local_host_ip}\", ${result_master_ip},${result_slave_ip}],\"action\":\"deny\"}' http://${env_test}/v1.0/${auth_token_pin}/acl"
echo "${test_cases}"
result=`eval ${test_cases}`
echo "[RESULT] ${result}"
echo ""

code=`echo ${result} | jq .code`

if [ ${code} == "null" ] || [ ${code} != "1" ];then
        msg=`echo ${result} | jq .msg`
        echo "[ERROR] 【设置ACL访问列表失败】${msg}"
        echo ""
fi

sleep "${wait_time_long}"

### 查看ACL设置 ###
test_cases="curl -s -H\"auth-Token:${auth_token}\" -XGET http://${env_test}/v1.0/${auth_token_pin}/acl/${space_id}"
echo "${test_cases}"
result=`eval ${test_cases}`
echo "[RESULT] ${result}"
echo ""

code=`echo ${result} | jq .code`

if [ ${code} == "null" ] || [ ${code} != "1" ];then
        msg=`echo ${result} | jq .msg`
        echo "[ERROR] 【查看ACL访问列表失败】${msg}"
        echo ""
fi
#set -x
ips=`echo ${result} | jq .attach.ips`
if [ "null" = ${ips} ];then
	echo "[INFO] 设置deny成功 "
fi
echo ""
#set +x
