#!/bin/bash
###########################################################
### DESC:创建缓存云实例，并根据创建的space_id查看创建的结果
### INTERFACE: http://ip:port/v1.0/{pin}/clusters
### METHOD: POST
### INTERFACE: http://ip:port/v1.0/{pin}/clusters/{space_id}
### METHOD: GET
### AUTHER: guoli
### DATE: 06/09/2016
### VERSION: 1.0
###########################################################

### 依赖：系统中安装jq ###

### 环境 ###
# 测试环境 #
env_test="192.168.177.88"
# 线上环境 #
#env_test="jdicts-jcache-hb.jcloud.com"

### jimdbtest 测试环境的测试账号 ##
#auth_token="K1AwANjwaBmIWZBBHadr6oLC3AEIAkAtqhAJofH+ZZw="
#auth_token_pin="64c8ddb08ad83c7b04fba541c3b085fd"

### 线上环境的测试账号 ###
#auth_token=" FwTMH6WMOcYnG4CC9M0tb/6lQWYxnhaOGxqzG0j5T7Q="
#auth_token_pin="fc62fd6aedacef996b28be508faa1f58"

### 测试环境的测试账号 ###
auth_token="58pSCQhqyE43rgKDsb1uXaBQGFERi1lS3hxAPzrF2rY="
auth_token_pin="f22fcf7ff03d27f00491ee14299b88ca"

### 等待时间 ###
wait_time_long="5"
wait_time_short="3"

space_type="1"
quantity="1"

### 创建缓存云实例 ###
echo "创建缓存云实例"
test_cases="curl -s -H\"auth-Token:${auth_token}\" -H\"Content-Type:application/json\" -XPOST --data '{\"spaceName\":\"\",\"spaceType\":${space_type},\"zoneId\":1,\"capacity\":2097152,\"quantity\":${quantity},\"remarks\":\"\"}' http://${env_test}/v1.0/${auth_token_pin}/clusters"
echo "${test_cases}"
result=`eval ${test_cases}`
echo "[RESULT] ${result}"
echo ""

### 根据code判断缓存云是否创建成功: code=1创建成功,code=0创建失败 ###
code=`echo ${result} | jq .code`
#echo "code=${code}"
#echo ""

if [ ${code} -ne 1 ];then
        msg=`echo ${result} | jq .msg`
        echo "[ERROR]【缓存云实例创建失败】: ${msg}"
	echo ""
        exit 0
fi

### 缓存云创建成功后，attach为创建的对应的space_id ###
space_id=`echo ${result} | jq .attach`
echo "[INFO] 实例space_id=${space_id}被创建."
echo ""

### 根据space_id查找对应的缓存云实例 ###
echo "根据space_id查找对应的缓存云实例"
test_cases="curl -s -H\"auth-Token:${auth_token}\" -XGET http://${env_test}/v1.0/${auth_token_pin}/clusters/${space_id}"
echo "${test_cases}"
result=`eval ${test_cases}`
echo "[RESULT] ${result}"
echo ""

### 查询是否成功 ###
code=`echo ${result} | jq .code`
#echo "code=${code}"
#echo ""

if [ ${code} -ne 1 ];then
        msg=`echo ${result} | jq .msg`
        echo "[ERROR]【根据space_id查询缓存云实例错误】: ${msg}"
        exit 0
fi

sleep ${wait_time_short}

### 根据space_id查询缓存云实例的创建状态：status=100创建成功，status=500创建失败 ###
result=`eval ${test_cases}`
status=`echo ${result} | jq .attach.status`
#echo "status=${status}"
#echo ""

while [[ 1 -eq 1 ]];do
        result=`eval ${test_cases}`
        status=`echo ${result} | jq .attach.status`
        #echo "${status}"
	if [ ${status} == "null" ];then
		echo ""
		echo "[ERROR] 创建失败"
		echo ""
		break
	fi
        if [ ${status} -eq 100 ];then
		echo ""
		echo "[INFO] 创建成功"
		echo ""
                break
        fi
	if [ ${status} -eq 500 ];then
		echo ""
		echo "[ERROR] 创建失败"
		echo ""
		break
	fi
	if [ ${status} -eq 0 ];then
		echo "[INFO] 创建中..."
	fi

        sleep ${wait_time_long}
done

echo ""

echo "[STEP] 查询数据库表中的topology表，查看space_id=${space_id}的master和slave信息"
### Mysql数据库信息 ###
MYSQL_HOSTNAME="192.168.177.87"
MYSQL_PORT="3306"
MYSQL_USERNAME="tester"
MYSQL_PASSWORD="123456"
MYSQL_DBNAME="jimdb"

### 查询数据库中topology表 ###
sql_select_topology=`mysql -h${MYSQL_HOSTNAME} -u${MYSQL_USERNAME} -p${MYSQL_PASSWORD} << EOF
        use ${MYSQL_DBNAME};
        select current_topology from topology where space_id=${space_id};
EOF`

#set -x
result=`echo ${sql_select_topology} | sed -e 's/current_topology//g' | sed 's/^[ \t]*//g'`
echo "[RESULT] ${result}"
echo ""
#set +x

### 缓存云实例的master的IP&Port ###
container_master_ip=`echo ${result} | jq .shards[0].master.ip`
container_master_port=`echo ${result} | jq .shards[0].master.port`
echo "[INFO] 缓存云实例space_id=${space_id}的master的IP:Port=${container_master_ip}:${container_master_port}"
echo ""

### 缓存云实例的slave的IP&Port ###
container_slave_ip=`echo ${result} | jq .shards[0].master.slaves[0].ip`
container_slave_port=`echo ${result} | jq .shards[0].master.slaves[0].port`
echo "[INFO] 缓存云实例space_id=${space_id}的slave的IP:Port=${container_slave_ip}:${container_slave_port}"
echo ""

