#!/bin/bash
#################################################
### SCENARIO:并发创建5个缓存云实例
###	     查询缓存云实例status=100创建成功
###	     并发删除5个缓存云实例
#################################################

### 依赖：系统中安装jq ###

### 环境 ###
env_test="192.168.177.88"

### jimdbtest ###
auth_token="K1AwANjwaBmIWZBBHadr6oLC3AEIAkAtqhAJofH+ZZw="
auth_token_pin="64c8ddb08ad83c7b04fba541c3b085fd"

### JaneCloud002/123456 ###
#auth_token="FwTMH6WMOcYnG4CC9M0tb/6lQWYxnhaOGxqzG0j5T7Q="
#auth_token_pin="fc62fd6aedacef996b28be508faa1f58"

### 等待时间 ###
wait_time_long="5"
wait_time_short="3"

concurrent_times="5"

### 失败创建的实例数 ###
failed_instance_created=0

### 删除失败的实例数 ###
failed_instance_deleted=0

space_type="1"
quantity="1"

### Mysql数据库信息 ###
MYSQL_HOSTNAME="192.168.177.87"
MYSQL_PORT="3306"
MYSQL_USERNAME="tester"
MYSQL_PASSWORD="123456"
MYSQL_DBNAME="jimdb"

for ((i=0;i<${concurrent_times};i++))
do
### 创建缓存云实例 ###
echo "[STEP] 创建缓存云实例"
test_cases="curl -s -H\"auth-Token:${auth_token}\" -H\"Content-Type:application/json\" -XPOST --data '{\"spaceName\":\"\",\"spaceType\":${space_type},\"zoneId\":1,\"capacity\":2097152,\"quantity\":${quantity},\"remarks\":\"\"}' http://${env_test}/v1.0/${auth_token_pin}/clusters"
echo "${test_cases}"
result=`eval ${test_cases}`
echo "[RESULT] ${result}"
echo ""

space_id_array[i]=`echo ${result} | jq .attach`
echo "[INFO] 实例space_id=${space_id_array[i]}被创建."
echo ""
done

### 查询缓存云实例是否创建成功 ###
for ((i=0;i<${concurrent_times};i++))
do
echo "[STEP] 查询缓存云实例space_id=${space_id_array[i]}是否创建成功的状态"
test_cases="curl -s -H\"auth-Token:${auth_token}\" -XGET http://${env_test}/v1.0/${auth_token_pin}/clusters/${space_id_array[i]}"
echo "${test_cases}"
result=`eval ${test_cases}`
echo "[RESULT] ${result}"
echo ""

### 查询是否成功 ###
code=`echo ${result} | jq .code`
#echo "code=${code}"
#echo ""

if [ ${code} -ne 1 ];then
        msg=`echo ${result} | jq .msg`
        echo "[ERROR]【根据space_id查询缓存云实例错误】: ${msg}"
        exit 0
fi

sleep ${wait_time_short}

### 根据space_id查询缓存云实例的创建状态：status=100创建成功，status=500创建失败 ###
result=`eval ${test_cases}`
status=`echo ${result} | jq .attach.status`
#echo "status=${status}"
#echo ""

if [ ${status} == "null" ];then
        echo "[INFO] space_id=${space_id_array[i]}已经被删除"
        echo ""
        exit 0
fi

while [[ 1 -eq 1 ]];do
        result=`eval ${test_cases}`
        status=`echo ${result} | jq .attach.status`
        #echo "${status}"
        if [ ${status} == "0" ];then
                echo "[INFO] ${space_id_array[i]}创建中..."
		
        fi
        if [ ${status} == "100" ];then
                echo ""
                echo "[INFO] ${space_id_array[i]}创建成功"
                echo ""
                break
        fi
        if [ ${status} == "500" ];then
		failed_instance_created=${failed_instance_created+1}
                echo ""
                echo "[INFO] ${space_id_array[i]}创建失败"
                eicho ""
                break
        fi
        sleep ${wait_time_short}
done
echo ""
done

sleep ${wait_time_long}

### 删除缓存云实例 ###
for ((i=0;i<${concurrent_times};i++))
do
echo "[STEP] 删除缓存云实例space_id=${space_id_array[i]}"
test_cases="curl -s -H\"auth-Token:${auth_token}\" -XDELETE http://${env_test}/v1.0/${auth_token_pin}/clusters/${space_id_array[i]}"
echo "${test_cases}"
result=`eval ${test_cases}`
echo "[RESULT] ${result}"
echo ""

#code=`echo ${result} | jq .code`

#if [ ${code} != "1" ];then
#        msg=`echo ${result} | jq .msg`
#        echo "[ERROR] ${msg}"
#        echo ""
#fi

done

### 查询缓存云实例是否被删除成功 ###
for ((i=0;i<${concurrent_times};i++))
do
echo "[STEP] 查询缓存云space_id=${space_id_array[i]}实例的状态"
test_cases="curl -s -H\"auth-Token:${auth_token}\" -XGET http://${env_test}/v1.0/${auth_token_pin}/clusters/${space_id_array[i]}"
echo "${test_cases}"
result=`eval ${test_cases}`
echo "[RESULT] ${result}"
echo ""

### 查询是否成功 ###
code=`echo ${result} | jq .code`
#echo "code=${code}"
#echo ""

if [ ${code} != "1" ];then
        msg=`echo ${result} | jq .msg`
        echo "[ERROR]【根据space_id查询缓存云实例错误】: ${msg}"
        echo ""
        exit 0
fi

status=`echo ${result} | jq .attach.status`
#echo "status=${status}"
if [ ${status} == "null" ];then
        echo "[INFO] space_id=${space_id_array[i]}该实例已被删除"
        echo ""
        #exit 0
fi

#while [[ 1 -eq 1 ]];do
#        result=`eval ${test_cases}`
#        #attach=`echo ${result} | jq .attach`
#        #if [ ! -n ${attach} ];then
#        #       echo ""
#        #       echo "[INFO] ${space_id_array[i]}删除成功"
#        #       break
#        #fi
#        status=`echo ${result} | jq .attach.status`
#        if [ ${status} == "null" ];then
#		#failed_instance_deleted=${failed_instance_deleted+1}	
#                echo ""
#                echo "[INFO] ${space_id_array[i]}删除成功"
#                break
#        fi
#        if [ ${status} == "601" ];then
#                echo ""
#                echo "[INFO] ${space_id_array[i]}删除成功"
#                break
#        fi
#        if [ ${status} == "600" ];then
#		#failed_instance_deleted=${failed_instance_deleted+1}
#                echo "[INFO] ${space_id_array[i]}删除中..."
#        fi
#	if [ ${status} == "602" ];then
#		echo "[INFO] ${space_id_array[i]}删除失败"
#		break
#	fi
#        sleep ${wait_time_long}
#done

while [[ 1 -eq 1 ]];do
sql_select_topology=`mysql -h${MYSQL_HOSTNAME} -u${MYSQL_USERNAME} -p${MYSQL_PASSWORD} << EOF
        use ${MYSQL_DBNAME};
        select status from space where id=${space_id_array[i]};
EOF`

status=`echo ${sql_select_topology} | sed -e 's/status//g' | sed 's/^[ \t]*//g'`

if [ "600" = "${status}" ];then
	echo "[INFO] 删除中..."
fi

if [ "601" = "${status}" ];then
	echo "[INFO] space_id=${space_id_array[i]}删除成功"
	echo ""
	break
fi

if [ "602" = "${status}" ];then
	failed_instance_deleted=${failed_instance_deleted+1}
	echo "[ERROR] space_id=${space_id_array[i]}删除失败"
	echo ""
	break
fi

if [ "null" = "${status}" ];then
	failed_instance_deleted=${failed_instance_deleted+1}
	echo "[ERROR] space_id=${space_id_array[i]}删除失败"
	echo ""
	break
fi

sleep ${wait_time_long}
done

echo ""
done

echo "[RESULT] 执行了${concurrent_times},创建失败数量${failed_instance_created}"
echo ""
echo "[RESULT] 执行了${concurrent_times},删除失败的数量${failed_instance_deleted}"
echo ""
