#!/bin/bash
##################################################
### DESC: stop slave后，failover将创建新的slave
###	  资源，并将新的slave指派给master,并且
###	  将master的数据拷贝到新的slave上
### DB: topology,instance,space
### Docker container:实例对应的container
### CFS：记录缓存云实例的信息
### AP：实际可访问的资源代理
##################################################

space_id="$1"

### 依赖：系统中安装jq ###

### 输入参数个数小于1，不执行本脚本 ###
if [ $# -lt 1 ];then
        echo "[WARNING] 请输入space id"
        exit 0
fi

### 环境 ###
env_test="192.168.177.88"

### Docker Container ###
docker_container_ip_1="192.168.177.89"
docker_container_ip_2="192.168.169.51"

### CFS ###
cfs_ip="192.168.177.87"

### AP ###
ap_ip="192.168.177.89"

auth_token="K1AwANjwaBmIWZBBHadr6oLC3AEIAkAtqhAJofH+ZZw="
auth_token_pin="64c8ddb08ad83c7b04fba541c3b085fd"

space_id="$1"

wait_time_long="5"
wait_time_short="2"

failover_times="10"

### Mysql数据库信息 ###
MYSQL_HOSTNAME="192.168.177.87"
MYSQL_PORT="3306"
MYSQL_USERNAME="tester"
MYSQL_PASSWORD="123456"
MYSQL_DBNAME="jimdb"

### 查询数据库中topology表 ###
sql_select_topology=`mysql -h${MYSQL_HOSTNAME} -u${MYSQL_USERNAME} -p${MYSQL_PASSWORD} << EOF
        use ${MYSQL_DBNAME};
        select current_topology from topology where space_id=${space_id};
EOF`

result=`echo ${sql_select_topology} | sed -e 's/current_topology//g' | sed 's/^[ \t]*//g'`
echo "[RESULT] ${result}"
echo ""

### 缓存云实例的master的IP&Port ###
container_master_ip=`echo ${result} | jq .shards[0].master.ip`
container_master_port=`echo ${result} | jq .shards[0].master.port`
echo "[INFO] 缓存云实例space_id=${space_id}的master的IP:Port=${container_master_ip}:${container_master_port}"
echo ""

### 缓存云实例的slave的IP&Port ###
container_slave_ip=`echo ${result} | jq .shards[0].master.slaves[0].ip`
container_slave_ip=`echo ${container_slave_ip} | sed 's/^[\"\t]*//g' | sed 's/[\"\t]*$//g'`
container_slave_port=`echo ${result} | jq .shards[0].master.slaves[0].port`
echo "[INFO] 缓存云实例space_id=${space_id}的slave的IP:Port=${container_slave_ip}:${container_slave_port}"
echo ""
for ((i=0;i<${failover_times};i++))
do
### 调用expect来stop缓存云实例的slave ###
#if [ "192.168.177.89" = ${container_slave_ip} ];then
#	echo "[STEP] stop缓存云实例${space_id}的slave"
#	eval ./remote_docker_container ${container_slave_port}
#
#	echo ""
#fi
#
#if [ "192.168.169.51" = ${container_slave_ip} ];then
#	echo "[STEP] stop缓存云实例${space_id}的slave"
#	eval ./remote_docker_container_51 ${container_slave_port}
#	echo ""
#fi
echo "[STEP] stop缓存云实例${space_id}的slave，ip:port=${container_slave_ip}:${container_slave_port}"
eval ./remote_docker_container ${container_slave_ip} ${container_slave_port}

sleep ${wait_time_long}

### 查询数据库中topology表 ###
echo "[STEP] 查询数据库表topology表中，缓存云实例space_id=${space_id}的master和slave信息"
while [[ 1 -eq 1 ]];do
sql_select_topology=`mysql -h${MYSQL_HOSTNAME} -u${MYSQL_USERNAME} -p${MYSQL_PASSWORD} << EOF
        use ${MYSQL_DBNAME};
        select current_topology from topology where space_id=${space_id};
EOF`	
	
	result=`echo ${sql_select_topology} | sed -e 's/current_topology//g' | sed 's/^[ \t]*//g'`
	### 缓存云实例的master的IP&Port ###
	container_master_ip=`echo ${result} | jq .shards[0].master.ip`
	container_master_port=`echo ${result} | jq .shards[0].master.port`

	### 缓存云实例的slave的IP&Port ###
	container_slave_ip_new=`echo ${result} | jq .shards[0].master.slaves[0].ip`
	container_slave_ip_new=`echo ${container_slave_ip} | sed 's/^[\"\t]*//g' | sed 's/[\"\t]*$//g'`
	container_slave_port_new=`echo ${result} | jq .shards[0].master.slaves[0].port`
#	set -x
	if [ "${container_slave_port}" != "${container_slave_port_new}" ];then
		echo "[INFO] 新的slave：${container_slave_ip_new}:${container_slave_port_new}被创建"
		echo ""
		container_slave_port=${container_slave_port_new}
#		echo "==== ${container_slave_port}"
		break
	fi
	echo "[INFO] failover正在为缓存云实例space_id=${space_id}创建新的slave..."
#	set +x
	echo ""
	sleep ${wait_time_long}
done

echo "[INFO] failover为缓存云实例space_id=${space_id}创建新的slave的IP:Port=${container_slave_ip_new}:${container_slave_port_new}"
echo ""

sleep ${wait_time_short}
echo ""
done
echo ""
